"""changed datetime to only date in transactions

Revision ID: 774a5f04bd5b
Revises: d661da11ebcb
Create Date: 2026-04-22 20:41:23.065860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774a5f04bd5b'
down_revision: Union[str, Sequence[str], None] = 'd661da11ebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
